/*
Time : Thu Oct 19 2017 20:10:46 GMT+0530 (IST)
URL : https://www.interviewbit.com/problems/repeating-subsequence/#
Given a string, find if there is any sub-sequence that repeats itself.
A sub-sequence of a string 
is defined as a sequence of characters generated by deleting some characters in the string without 
changing the order of the remaining characters.

Input:
string

Output:

0/1
0 -> No
1 -> Yes 
Example:

abab 
------> yes, ab is repeated. So, return 1. 
abba ------> No, a and b follow different order. So, 
return 0. 
NOTE : sub-sequence length should be greater than or equal to 2

*/

#include <bits/stdc++.h>

using namespace std;

#define vi vector<int>
#define vvi vector<vi>
#define vr vector

int Solution::anytwo(string s) {
    int l = s.length();
    vvi mem(l+1, vi(l+1,0));
    for(int i=1;i<=l;i++){
        for(int j=1;j<=l;j++){
            if(s[i-1]==s[j-1] && i!=j)mem[i][j] = 1+ mem[i-1][j-1];
            else mem[i][j] = max(mem[i][j-1], mem[i-1][j]);
        }
    }
    return mem[l][l]>=2;
}


int main(){

	return 0;
}
